type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  bio: String
  profilePictureUrl: String
  websiteUrl: String
  linkedInUrl: String
  gitHubUrl: String
  twitterUrl: String
}

type Project @table {
  user: User
  title: String!
  description: String!
  createdAt: Timestamp!
  imageUrl: String
  projectUrl: String
  repositoryUrl: String
  category: String
  technologiesUsed: [String]
}

type Skill @table {
  user: User
  name: String!
  createdAt: Timestamp!
  category: String
  proficiencyLevel: String
}

type Experience @table {
  user: User
  type: String!
  title: String!
  organization: String!
  startDate: Date!
  createdAt: Timestamp!
  description: String
  endDate: Date
  location: String
  degree: String
  role: String
}

type PortfolioSetting @table {
  user: User
  isPublic: Boolean!
  createdAt: Timestamp!
  theme: String
  layout: String
}